[pytest]
asyncio_mode = auto
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

[coverage:run]
source = app
omit =
    app/tests/*
    app/database/migrations/*

[coverage:report]
skip_empty = true
show_missing = true
